server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # Connection timeout badhaya hai taaki 500 error na aaye
      httpclient:
        connect-timeout: 10000
        response-timeout: 30s
      globalcors:
        add-to-gateway-request-chain: true
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: user-service
          # lb:// hata kar seedha URL diya hai timeout se bachne ke liye
          uri: https://ecoride-deploy-user.onrender.com
          predicates:
            - Path=/users/**

        - id: ride-service
          uri: https://ecoride-ride-service.onrender.com
          predicates:
            - Path=/rides/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:https://service-registry-qhsy.onrender.com/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    hostname: api-gateway-n7gy.onrender.com
    # Is line ko rehne dete hain par URI preference seedhi HTTPS par hai
    non-secure-port: ${server.port}